### ISSUE TITLE
error: Search plugin bootstrap failed. Search plugin could not load provider 'algolia': Cannot find module '@mattie-bundle/strapi-provider-search-algolia'

### ISSUE THREAD

**Issue by 3webbg** [MattieBelt/mattie-strapi-bundle#50]
Hello,
i use Strapi v4.0.4 and "@mattie-bundle/strapi-plugin-search": "^1.0.0-alpha.2",
I have set the plugin correctly, but after trying to start i have this error: error: Search plugin bootstrap failed. Search plugin could not load provider 'algolia': Cannot find module '@mattie-bundle/strapi-provider-search-algolia'

Image: [https://ibb.co/WK7wSfC](url)

**Comment by 3webbg** [comment]
@mfozmen 

I have same config:

` search: {
    enabled: true,
    config: {
      provider: "algolia",
      providerOptions: {
        apiKey: env("ALGOLIA_PROVIDER_ADMIN_API_KEY"),
        applicationId: env("ALGOLIA_PROVIDER_APPLICATION_ID"),
      },
      contentTypes: [
        { name: "api::product.product" },
        { name: "api::category.category" },
      ],
    },
  },`

Unfortunately, it still doesn't work.
Ref image: https://ibb.co/0rp2L34

**Comment by mfozmen** [comment]
I also installed strapi-provider-search-algolia package. Can you try installing it?

**Comment by 3webbg** [comment]
@mfozmen 
Unfortunately, it still doesn't work for me.
I tried different configurations, versions of the plugin, but it still doesn't work. 
I hope to have an update on this project soon, because it is important for me to be able to use this plugin  :(

**Comment by MattieBelt** [comment]
Hey @3webbg,

Sorry for my delayed response, I could reproduce the error you received installing the plugin and it's provider.
I took the following steps:
1. Create a fresh project with `yarn create strapi-app my-project --quickstart`
2. Add the Search plugin package with `yarn add @mattie-bundle/strapi-plugin-search`
3. Add the config to the `plugins.js` file:
```js
module.exports = ({ env }) => ({
    search: {
      enabled: true,
      config: {
        provider: 'algolia',
        providerOptions: {
          apiKey: env('ALGOLIA_PROVIDER_ADMIN_API_KEY'),
          applicationId: env('ALGOLIA_PROVIDER_APPLICATION_ID'),
        },
        contentTypes: [{ name: 'api::podcast.podcast' }, { name: 'api::episode.episode' }, { name: 'api::category.category' }],
      },
    },
  });
```
4. Run Strapi server `yarn develop` and receive error:
```text
error: Search plugin bootstrap failed. Search plugin could not load provider 'algolia': Cannot find module '@mattie-bundle/strapi-provider-search-algolia'
```

But this Error is an expected error as @mfozmen suggested,
> I also installed strapi-provider-search-algolia package. Can you try installing it?

you can solve this by adding the Algolia provider package to your project. You can do that with `yarn add @mattie-bundle/strapi-provider-search-algolia` or `npm install @mattie-bundle/strapi-provider-search-algolia`.

This search plugin is set up in a way that it can have different providers for different kind of Search services, in the future I for example hope to add a different provider for Elasticsearch and Meilisearch, but other community members are also open to create there own community search provider, just like the email and upload system Strapi is using. 

Let me know if this solves your problem and we can solve this issue.

**Comment by MattieBelt** [comment]
I'm closing this issue as the above comment should resolve this.

Let me know if you are still having problems and I'm happy to reopen this.
