### ISSUE TITLE
Various peer dependency issues

### ISSUE THREAD

**Issue by Adarah** [MattieBelt/mattie-strapi-bundle#52]
Hi, I'm trying to use both of your packages (1.0.0-alpha.2) on strapi 4.0.4, but I'm getting various peer dependency conflicts upon `npm install`. It seems that `@mattie-bundle/strapi-provider-search-algolia` depends on version 1.0.0-alpha.0 of `@mattie-bundle/strapi-plugin-search`, which in turn depends on `"@strapi/strapi": "4.0.0-beta.0"`.

The relevant parts of my package.json currently looks like this
```json
    "@mattie-bundle/strapi-plugin-search": "^1.0.0-alpha.2",
    "@mattie-bundle/strapi-provider-search-algolia": "^1.0.0-alpha.2",
    "@strapi/design-system": "^0.0.1-alpha.71",
    "@strapi/plugin-i18n": "4.0.4",
    "@strapi/plugin-users-permissions": "4.0.4",
    "@strapi/strapi": "4.0.4",
```

**Comment by 3webbg** [comment]
@Adarah 
I have the same problem. The quick solution is to use `yarn`

**Comment by MattieBelt** [comment]
Hey @Adarah, thanks for reporting this issue. As @3webbg yarn indeed doesn't conflict about these differences. I will update the peerDependencies in the next patch.
